import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import {
  MAP_BOUNDARY,
  MAP_CHESTS,
  MAP_GEOMETRY_HASH,
  MAP_MONSTER_SLOTS,
  MAP_NESTS,
  MAP_ROUTE_NODES,
  MAP_SPAWN_POINTS,
  MAP_STRUCTURE_PIECES,
  MAP_STRUCTURES_HASH,
  type MapConvexPieceRecord,
} from '@jwgb/content';
import { createMapCollisionField, MapCollisionField } from '@jwgb/sim';
import { describe, expect, it } from 'vitest';
import { structureCollisionFootprints } from '../apps/web/src/render/map/map-asset-layer';

const ROOT = resolve(import.meta.dirname, '..');
const GENERATED_PATH = resolve(ROOT, 'packages/content/src/map-structures.generated.ts');
const MANIFEST_PATH = resolve(ROOT, 'apps/web/public/models/map-assets/manifest.json');
/** Same seed the map environment derives from the geometry hash at runtime. */
const RUNTIME_SEED = Number.parseInt(MAP_GEOMETRY_HASH.slice(0, 8), 16) >>> 0 || 1;
const PLAYER_RADIUS_MM = 450;

interface ManifestAsset {
  readonly id: string;
  readonly metrics: { readonly normalized: { readonly bounds: readonly number[] } };
}

function manifestBounds(): ReadonlyMap<string, readonly number[]> {
  const manifest = JSON.parse(readFileSync(MANIFEST_PATH, 'utf8')) as { assets: ManifestAsset[] };
  return new Map(manifest.assets.map((asset) => [asset.id, asset.metrics.normalized.bounds]));
}

function crossOrientation(
  a: { x: number; z: number },
  b: { x: number; z: number },
  p: { x: number; z: number },
): number {
  return (b.x - a.x) * (p.z - a.z) - (b.z - a.z) * (p.x - a.x);
}

function expectedPieces(): readonly MapConvexPieceRecord[] {
  return structureCollisionFootprints(RUNTIME_SEED, manifestBounds()).map((footprint) => {
    const vertices = footprint.vertices.map((vertex) => ({
      x: Math.round(vertex.x * 1_000),
      z: Math.round(vertex.z * 1_000),
    }));
    // Sim-CCW: every edge must keep interior points on its non-negative side.
    let area = 0;
    for (let index = 0; index < vertices.length; index += 1) {
      const a = vertices[index] as { x: number; z: number };
      const b = vertices[(index + 1) % vertices.length] as { x: number; z: number };
      area += a.x * b.z - b.x * a.z;
    }
    if (area < 0) {
      vertices.reverse();
    }
    const heightMm = Math.round(footprint.heightMeters * 1_000);
    return {
      pieceId: `structure:${footprint.id}`,
      wallId: footprint.assetId,
      wallClass: 'STRUCTURE',
      heightMm,
      blinkPassable: false,
      flightPassable: true,
      vertices,
    };
  });
}

function tableHash(pieces: readonly MapConvexPieceRecord[]): string {
  return createHash('sha256').update(JSON.stringify(pieces)).digest('hex').slice(0, 16);
}

function renderTable(pieces: readonly MapConvexPieceRecord[]): string {
  const rows = pieces
    .map(
      (piece) =>
        `  {\n    pieceId: '${piece.pieceId}',\n    wallId: '${piece.wallId}',\n    wallClass: '${piece.wallClass}',\n` +
        `    heightMm: ${piece.heightMm},\n    blinkPassable: ${piece.blinkPassable},\n    flightPassable: ${piece.flightPassable},\n` +
        `    vertices: [${piece.vertices.map((v) => `{ x: ${v.x}, z: ${v.z} }`).join(', ')}],\n  },`,
    )
    .join('\n');
  return (
    '// Generated by tests/map-structures.test.ts (JWGB_WRITE_MAP_STRUCTURES=1). Do not edit.\n' +
    "import type { MapConvexPieceRecord } from './map-geometry-types';\n\n" +
    '/** Hash of the structure footprint table below, mixed into the collision field hash. */\n' +
    `export const MAP_STRUCTURES_HASH = '${tableHash(pieces)}';\n\n` +
    '/**\n * Building footprints the simulation treats as solid ground obstacles. Each\n' +
    ' * piece is the rotated plinth rectangle of one placed building, in integer mm,\n' +
    ' * sim-CCW, so the authoritative field needs no trigonometry to use them.\n */\n' +
    `export const MAP_STRUCTURE_PIECES: readonly MapConvexPieceRecord[] = [\n${rows}\n];\n`
  );
}

describe('map structure footprints', () => {
  it('matches the generated table (set JWGB_WRITE_MAP_STRUCTURES=1 to regenerate)', () => {
    const expected = expectedPieces();
    if (process.env.JWGB_WRITE_MAP_STRUCTURES === '1') {
      writeFileSync(GENERATED_PATH, renderTable(expected));
    }
    expect(expected.length).toBeGreaterThan(60);
    expect(MAP_STRUCTURE_PIECES).toEqual(expected);
    expect(MAP_STRUCTURES_HASH).toBe(tableHash(expected));
  });

  it('keeps every piece a sim-CCW convex quad of sane size', () => {
    for (const piece of MAP_STRUCTURE_PIECES) {
      expect(piece.vertices).toHaveLength(4);
      for (let index = 0; index < 4; index += 1) {
        const a = piece.vertices[index] as { x: number; z: number };
        const b = piece.vertices[(index + 1) % 4] as { x: number; z: number };
        const c = piece.vertices[(index + 2) % 4] as { x: number; z: number };
        expect(crossOrientation(a, b, c)).toBeGreaterThan(0);
        expect(Math.hypot(b.x - a.x, b.z - a.z)).toBeLessThan(40_000);
      }
      expect(piece.heightMm).toBeGreaterThan(2_000);
    }
  });

  it('never buries a spawn, chest, monster slot, nest or route node inside a building', () => {
    const field = new MapCollisionField('structures-only', MAP_BOUNDARY, MAP_STRUCTURE_PIECES);
    const points = [
      ...MAP_SPAWN_POINTS.map((spawn) => ({ label: `spawn ${spawn.id}`, ...spawn.position })),
      ...MAP_CHESTS.map((chest, index) => ({ label: `chest ${index}`, ...chest.position })),
      ...MAP_MONSTER_SLOTS.map((slot, index) => ({ label: `slot ${index}`, ...slot.position })),
      ...MAP_NESTS.map((nest, index) => ({ label: `nest ${index}`, ...nest.base })),
      ...MAP_ROUTE_NODES.map((node) => ({ label: `route ${node.id}`, ...node.position })),
    ];
    const buried = points.filter((point) =>
      field.isCircleBlocked({ x: point.x, z: point.z }, PLAYER_RADIUS_MM),
    );
    expect(buried.map((point) => point.label)).toEqual([]);
  });

  it('blocks walking into a hall but lets a player already inside walk out', () => {
    const field = createMapCollisionField();
    const piece = MAP_STRUCTURE_PIECES.find((item) => item.wallId === 'tang-hall');
    expect(piece).toBeDefined();
    if (!piece) {
      return;
    }
    const centre = {
      x: Math.trunc(piece.vertices.reduce((sum, v) => sum + v.x, 0) / 4),
      z: Math.trunc(piece.vertices.reduce((sum, v) => sum + v.z, 0) / 4),
    };
    expect(field.isCircleBlocked(centre, PLAYER_RADIUS_MM)).toBe(true);
    const outside = { x: centre.x + 20_000, z: centre.z };
    expect(field.isCircleBlocked(outside, PLAYER_RADIUS_MM)).toBe(false);
    // Walking in from open ground stops at the wall.
    const step = field.resolveMovement(
      outside,
      { x: centre.x + 2_000, z: centre.z },
      PLAYER_RADIUS_MM,
    );
    expect(field.isCircleBlocked(step, PLAYER_RADIUS_MM)).toBe(false);
    // A player who was inside when the footprints went live is not trapped.
    const exit = field.resolveMovement(
      centre,
      { x: centre.x + 600, z: centre.z },
      PLAYER_RADIUS_MM,
    );
    expect(exit).not.toEqual(centre);
  });
});
