// Generated by tools/content/compile-authoritative-content.ts. Do not edit.
namespace Jwgb.Content
{
    public enum RuntimeImplementationStatus : byte
    {
        Implemented = 1,
        DefinitionOnly = 2
    }

    public readonly struct AuthoritativeNamedRecord
    {
        public AuthoritativeNamedRecord(
            string id,
            string name,
            string category,
            RuntimeImplementationStatus runtimeStatus)
        {
            Id = id;
            Name = name;
            Category = category;
            RuntimeStatus = runtimeStatus;
        }

        public string Id { get; }
        public string Name { get; }
        public string Category { get; }
        public RuntimeImplementationStatus RuntimeStatus { get; }
    }

    public readonly struct AuthoritativeEquipmentRecord
    {
        public AuthoritativeEquipmentRecord(
            string id,
            string name,
            string rarity,
            string summary,
            RuntimeImplementationStatus runtimeStatus)
        {
            Id = id;
            Name = name;
            Rarity = rarity;
            Summary = summary;
            RuntimeStatus = runtimeStatus;
        }

        public string Id { get; }
        public string Name { get; }
        public string Rarity { get; }
        public string Summary { get; }
        public RuntimeImplementationStatus RuntimeStatus { get; }
    }

    public readonly struct AuthoritativeHeroRecord
    {
        public AuthoritativeHeroRecord(
            string id,
            string name,
            string template,
            string movementClass,
            string element,
            int level15Attack,
            int level15MaxHp,
            int level15MoveSpeedMmPerSecond,
            int attackRangeMm,
            int attacksPerSecondMilli,
            string activeName,
            int activeCooldownTicks,
            RuntimeImplementationStatus runtimeStatus)
        {
            Id = id;
            Name = name;
            Template = template;
            MovementClass = movementClass;
            Element = element;
            Level15Attack = level15Attack;
            Level15MaxHp = level15MaxHp;
            Level15MoveSpeedMmPerSecond = level15MoveSpeedMmPerSecond;
            AttackRangeMm = attackRangeMm;
            AttacksPerSecondMilli = attacksPerSecondMilli;
            ActiveName = activeName;
            ActiveCooldownTicks = activeCooldownTicks;
            RuntimeStatus = runtimeStatus;
        }

        public string Id { get; }
        public string Name { get; }
        public string Template { get; }
        public string MovementClass { get; }
        public string Element { get; }
        public int Level15Attack { get; }
        public int Level15MaxHp { get; }
        public int Level15MoveSpeedMmPerSecond { get; }
        public int AttackRangeMm { get; }
        public int AttacksPerSecondMilli { get; }
        public string ActiveName { get; }
        public int ActiveCooldownTicks { get; }
        public RuntimeImplementationStatus RuntimeStatus { get; }
    }

    public static class AuthoritativeContentCatalog
    {
        public const string Schema = "jwgb.authoritative-content.v1";
        public const string RulesetVersion = "3.1.0";
        public const int SkillCount = 101;
        public const int PveSimultaneousPopulation = 123;

        public static readonly AuthoritativeHeroRecord[] Heroes =
        {
            new AuthoritativeHeroRecord("H001", "铁扇公主", "连弩", "ground", "火", 110, 1650, 3400, 20000, 1600, "芭蕉风墙", 360, RuntimeImplementationStatus.Implemented),
            new AuthoritativeHeroRecord("H002", "红孩儿", "连弩", "ground", "火", 110, 1650, 3400, 20000, 1600, "三昧火墙", 480, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H003", "蜘蛛精", "连弩", "ground", "木", 110, 1650, 3400, 20000, 1600, "盘丝阵", 720, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H004", "蝎子精", "连弩", "ground", "土", 110, 1650, 3400, 20000, 1600, "倒马毒", 720, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H005", "多目怪", "长弓", "ground", "木", 134, 1550, 3200, 30000, 900, "金光", 600, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H006", "九头虫", "长弓·飞行", "flying", "水", 134, 1240, 3200, 30000, 900, "毒雾", 1100, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H007", "黄风怪", "连弩·飞行", "flying", "木", 110, 1320, 3400, 20000, 1600, "三昧神风", 1000, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H008", "太上老君", "长弓", "ground", "火", 134, 1550, 3200, 30000, 900, "八卦炉火", 1240, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H009", "孙悟空", "刺客", "ground", "金", 160, 1400, 3700, 5000, 1400, "大闹天宫", 800, RuntimeImplementationStatus.Implemented),
            new AuthoritativeHeroRecord("H010", "二郎神", "刺客", "ground", "金", 160, 1400, 3700, 5000, 1400, "天眼", 500, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H011", "哪吒", "刺客", "ground", "火", 160, 1400, 3700, 5000, 1400, "风火轮", 360, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H012", "六耳猕猴", "刺客", "ground", "金", 160, 1400, 3700, 5000, 1400, "六耳幻身", 840, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H013", "大鹏雕", "刺客·飞行", "flying", "金", 160, 1120, 3700, 5000, 1400, "金翅俯击", 400, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H014", "白骨精", "刺客", "ground", "土", 160, 1400, 3700, 5000, 1400, "借尸还魂", 700, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H015", "猪八戒", "战士", "ground", "水", 140, 1800, 3400, 5000, 1100, "九齿钉耙", 760, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H016", "白龙马", "战士", "ground", "水", 140, 1800, 3400, 5000, 1100, "龙马奔腾", 360, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H017", "青狮怪", "战士", "ground", "土", 140, 1800, 3400, 5000, 1100, "狮吼", 1200, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H018", "牛魔王", "战士", "ground", "火", 140, 1800, 3400, 5000, 1100, "旋风", 760, RuntimeImplementationStatus.Implemented),
            new AuthoritativeHeroRecord("H019", "独角兕大王", "战士", "ground", "金", 140, 1800, 3400, 5000, 1100, "金刚琢", 900, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H020", "黄眉老祖", "战士", "ground", "土", 140, 1800, 3400, 5000, 1100, "石罗汉", 1080, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H021", "金角大王", "战士", "ground", "金", 140, 1800, 3400, 5000, 1100, "紫金葫芦", 1120, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H022", "银角大王", "战士", "ground", "水", 140, 1800, 3400, 5000, 1100, "砸钱", 480, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H023", "黄袍怪", "战士", "ground", "木", 140, 1800, 3400, 5000, 1100, "缠身", 900, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H024", "虎力大仙", "战士", "ground", "火", 140, 1800, 3400, 5000, 1100, "虎箭", 700, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H025", "鹿力大仙", "战士", "ground", "木", 140, 1800, 3400, 5000, 1100, "鹿血", 900, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H026", "文殊菩萨", "战士", "ground", "金", 140, 1800, 3400, 5000, 1100, "定慧诀", 600, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H027", "普贤菩萨", "战士", "ground", "土", 140, 1800, 3400, 5000, 1100, "行愿", 840, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H028", "镇元大仙", "战士", "ground", "木", 140, 1800, 3400, 5000, 1100, "袖里乾坤", 1240, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H029", "如来佛祖", "坦克", "ground", "土", 100, 2200, 3000, 5000, 900, "五行山", 1400, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H030", "观音菩萨", "坦克", "ground", "木", 100, 2200, 3000, 5000, 900, "甘露", 1000, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H031", "托塔李天王", "坦克", "ground", "土", 100, 2200, 3000, 5000, 900, "宝塔", 2000, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H032", "唐僧", "坦克", "ground", "金", 100, 2200, 3000, 5000, 900, "袈裟", 1900, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H033", "沙和尚", "坦克", "ground", "水", 100, 2200, 3000, 5000, 900, "流沙", 1000, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H034", "黑熊精", "坦克", "ground", "木", 100, 2200, 3000, 5000, 900, "黑风罩", 1160, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H035", "白象精", "坦克", "ground", "水", 100, 2200, 3000, 5000, 900, "象鼻缚", 560, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H036", "灵感大王", "坦克", "ground", "水", 100, 2200, 3000, 5000, 900, "冻河", 680, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H037", "羊力大仙", "坦克", "ground", "木", 100, 2200, 3000, 5000, 900, "羊灵之光", 700, RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeHeroRecord("H038", "赛太岁", "坦克", "ground", "火", 100, 2200, 3000, 5000, 900, "迷烟", 560, RuntimeImplementationStatus.DefinitionOnly)
        };

        public static readonly AuthoritativeNamedRecord[] GenericActives =
        {
            new AuthoritativeNamedRecord("D1", "钩锁", "控制位移类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("D3", "雷击", "控制位移类", RuntimeImplementationStatus.Implemented),
            new AuthoritativeNamedRecord("D4", "变羊", "控制位移类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("D6", "闪现", "位移逃生类", RuntimeImplementationStatus.Implemented),
            new AuthoritativeNamedRecord("D7", "潜行", "位移逃生类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("D9", "箭雨", "AOE伤害类", RuntimeImplementationStatus.Implemented),
            new AuthoritativeNamedRecord("D10", "电链", "AOE伤害类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("D11", "轮盘", "AOE伤害类", RuntimeImplementationStatus.Implemented),
            new AuthoritativeNamedRecord("D12", "标记", "信息经济类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("D13", "换位", "信息经济类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("D14", "回溯", "信息经济类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("D15", "妙手空空", "信息经济类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("D16", "聚财", "信息经济类", RuntimeImplementationStatus.Implemented),
            new AuthoritativeNamedRecord("D17", "连赏", "信息经济类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("D18", "淘金狂热", "信息经济类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("D19", "豆兵", "召唤陷阱类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("D20", "陷阱", "召唤陷阱类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("D21", "冰棺", "召唤陷阱类", RuntimeImplementationStatus.Implemented),
            new AuthoritativeNamedRecord("D22", "铁布衫", "召唤陷阱类", RuntimeImplementationStatus.Implemented)
        };

        public static readonly AuthoritativeNamedRecord[] Passives =
        {
            new AuthoritativeNamedRecord("B1", "冰霜", "控制类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B2", "麻痹", "控制类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B3", "击退", "控制类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B4", "致盲", "控制类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B5", "眩晕", "控制类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B6", "暴击", "伤害类", RuntimeImplementationStatus.Implemented),
            new AuthoritativeNamedRecord("B7", "溅射", "伤害类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B8", "燃灰", "伤害类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B9", "毒素", "伤害类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B10", "斩杀", "伤害类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B11", "连击", "伤害类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B12", "狼灵", "伤害类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B13", "火灵", "伤害类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B14", "冷箭", "伤害类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B15", "闪避", "生存类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B16", "铁皮", "生存类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B17", "护盾", "生存类", RuntimeImplementationStatus.Implemented),
            new AuthoritativeNamedRecord("B18", "嗜血", "生存类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B19", "假死", "生存类", RuntimeImplementationStatus.Implemented),
            new AuthoritativeNamedRecord("B20", "复活", "生存类", RuntimeImplementationStatus.Implemented),
            new AuthoritativeNamedRecord("B21", "回复", "生存类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B22", "反伤", "反击类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B23", "反击", "反击类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B24", "吸收", "反击类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B25", "暴怒", "反击类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B26", "背刺", "战术类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B27", "疾跑", "战术类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B28", "猎杀", "战术类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B29", "伏击", "战术类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B30", "残影", "战术类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B31", "偷钱", "经济类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B32", "贪婪", "经济类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B33", "寻宝", "经济类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B34", "利息", "经济类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B35", "拾荒", "经济类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B36", "奔腾", "改规则类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B37", "共鸣", "改规则类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B38", "逆境", "改规则类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B39", "石像", "改规则类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B40", "强韧", "养成类", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B41", "赏金", "赏金体系", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B42", "悬赏", "赏金体系", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B43", "避雷", "天劫体系", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeNamedRecord("B44", "雷暴", "天劫体系", RuntimeImplementationStatus.DefinitionOnly)
        };

        public static readonly AuthoritativeEquipmentRecord[] Equipment =
        {
            new AuthoritativeEquipmentRecord("W1", "精铁棍", "white", "攻击+15 | 常见", RuntimeImplementationStatus.Implemented),
            new AuthoritativeEquipmentRecord("W2", "粗布战衣", "white", "生命+220 | 常见", RuntimeImplementationStatus.Implemented),
            new AuthoritativeEquipmentRecord("W3", "草鞋", "white", "移速+18（鞋） | 常见", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("W4", "铜护腕", "white", "攻击+10 生命+100 | 常见", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("W5", "轻甲背心", "white", "生命+110 移速+10 | 常见", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("W6", "行者束带", "white", "攻击+8 移速+10 | 常见", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("B1", "狼牙棒", "blue", "攻+20 | 对野怪伤害+30% | 常见", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("B2", "虎皮裙", "blue", "命+280 | 受普攻伤害-8 | 常见", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("B3", "避水珠", "blue", "命+200 | 受技能伤害-15% | 常见", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("B4", "定风珠", "blue", "命+200 | 被击退和拉扯的距离减半 | 罕见", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("B5", "药葫芦", "blue", "命+150 | 脱战时每秒回复8点 | 常见", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("B6", "磨刀石", "blue", "攻+12 | 暴击伤害+30% | 常见", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("B7", "铜镜", "blue", "命+200 | 受到的背刺/伏击加成伤害减半 | 罕见", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("B8", "聚宝袋", "blue", "命+120 | 击杀野怪+30金 | 常见", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("B9", "夜巡灯", "blue", "攻+10 | 视野范围+20% | 罕见", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("B10", "驭兽鞭", "blue", "攻+12 | 召唤物攻击+30% | 罕见", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("B11", "避雷木牌", "blue", "命+200 | 天劫对你的伤害-30% | 罕见", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("B12", "千里靴", "blue", "移速+26 | （纯速度，蓝档大鞋） | 常见", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("B13", "登云履", "blue", "移速+20 | 受到的减速效果减半（鞋） | 常见", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("P1", "七星剑", "purple", "攻+35 | 对生命低于30%的目标伤害+25% | 常见", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("P2", "火尖枪", "purple", "攻+28 | 普攻点燃目标2秒、每秒20点", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("P3", "幌金绳", "purple", "攻+18 | 你的硬控持续+0.5秒 | 罕见", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("P4", "人参果", "purple", "命+400 | 击杀英雄回复30%最大生命 | 常见", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("P5", "万年灵芝", "purple", "命+500 | 每秒回复8点 | 常见", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("P6", "风袋", "purple", "命+200 | 主动技能CD-20% | 常见", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("P7", "招魂幡", "purple", "攻+18 | 召唤物生命与攻击+60% | 罕见", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("P8", "布袋", "purple", "无属性 | 手牌格+1 | 稀有", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("P9", "照妖珠", "purple", "命+250 | 20米内隐身单位对你现形 | 罕见", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("P10", "赌坊金牌", "purple", "命+150 | 黑山老妖大赢概率翻倍 | 稀有", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("P11", "判官笔", "purple", "攻+25 | 击杀英雄时主动技能CD清零 | 罕见", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("P12", "荆棘甲", "purple", "命+400 | 反弹所受普攻伤害的20% | 罕见", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("P13", "夜行斗篷", "purple", "移速+25 | 静止2秒后隐身 | 罕见", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("P14", "血玉葫芦", "purple", "攻+25 | 普攻吸血10% | 常见", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("P15", "疾风靴", "purple", "移速+30 | 免疫减速（鞋） | 常见", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("G1", "九转金丹", "gold", "无属性 | 死亡瞬间原地满血复活+2秒无敌，", RuntimeImplementationStatus.Implemented),
            new AuthoritativeEquipmentRecord("G2", "混元珠", "gold", "攻+25 | 五行克制加成翻倍（+50%→+100%）", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("G3", "渡劫铃", "gold", "命+350 | 天劫对你的伤害降低70%", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("G4", "筋斗云", "gold", "移速+40 | 脱战5秒后升空飞行，进战落地（鞋）", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("G5", "聚宝盆", "gold", "无属性 | 所有金币收入+50%", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("G6", "降魔杵", "gold", "攻+60 | 对当前生命高于你的敌人伤害+25%", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("G7", "顺风耳", "gold", "命+300 | 全图敌人释放主动技能时，", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("G8", "雷公凿", "gold", "攻+20 | 攻速+40%（全游戏唯一攻速装备）", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("G9", "噬魂戒", "gold", "无属性 | 每次击杀永久+2攻击（击杀英雄+10），", RuntimeImplementationStatus.DefinitionOnly),
            new AuthoritativeEquipmentRecord("G10", "金箍棒", "gold", "攻+80 | 普攻射程+3米", RuntimeImplementationStatus.Implemented)
        };
    }
}
